const ROLES = Object.freeze({
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  NORMAL_USER: 'NORMAL_USER',
  STORE_OWNER: 'STORE_OWNER'
});

const VALIDATION = Object.freeze({
  NAME_MIN: 20,
  NAME_MAX: 60,
  ADDRESS_MAX: 400,
  PASSWORD_MIN: 8,
  PASSWORD_MAX: 16
});

module.exports = { ROLES, VALIDATION };
